# Site settings
baseurl = "http://10.0.0.22/"
languageCode = "en-us"
title = "Noise Machine"
theme = "hugrid"
# Enter your tracking code to enable Google Analytics
googleAnalytics = "UA-XXXXXXXX-Y"

contentdir = "content"
datadir = "data"
layoutdir = "layouts"
publishdir = "public"

[params]
    # Meta
    title = "Noise Machine"
    subtitle = ""
    author = "Zapic0"
    description = "Making raspberry sounds and talk since 2018"
    keywords = "raspberry, sounds, talk"
    raspberrypi = "raspberry.local"

    # Body background color
    bodybgcolor = "#f9f9f9"

    # Preview container button text
    buttontext = "PLAY"

    # Footer text
    footertext = ""

    # add extra-css
    # custom_css = ['css/extra1.css', 'css/extra2.css']